#!/bin/bash
set -e

TRASH='/tmp/trash'
# Note: the -rf, -fr should appear before -r and -f.
PATTERN="-fr -rf -r -f"

ARGS="$@"

for p in $PATTERN; do
    ARGS=${ARGS/$p /}
done

mkdir -p $TRASH
echo "Moving stuff to" $TRASH

mv $ARGS $TRASH
