#!/usr/bin/env python

import os
import sys
import shlex
import shutil

TRASH = '/tmp/trash'
PATTERNS="--recursive --force -fr -rf -r -f"

args = sys.argv[1:]

for pattern in PATTERNS.split():
    if pattern in args:
        args.remove(pattern)

if not os.path.exists(TRASH):
    os.makedirs(TRASH)

for path in args:
    print 'Moving %s to %s' % (path, TRASH)
    try:
        shutil.move(path, TRASH)
    except Exception:
        print 'Could not move', path
